# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AZ1dveM-SVRXeIi7VlsVw-gONKfC-uWv
"""

!pip install flask flask-ngrok pytesseract opencv-python scikit-learn pillow pdf2image numpy pandas

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
import pickle

# Create sample training data
data = {
    'repair_cost': [5000, 85000, 3000, 120000, 7000, 95000, 4000, 110000],
    'claim_age_days': [2, 45, 1, 60, 3, 50, 2, 70],
    'previous_claims': [0, 3, 0, 5, 0, 4, 1, 6],
    'location_match': [1, 0, 1, 0, 1, 0, 1, 0],
    'image_duplicate': [0, 1, 0, 1, 0, 1, 0, 1],
    'fraud': [0, 1, 0, 1, 0, 1, 0, 1]
}

df = pd.DataFrame(data)

X = df.drop('fraud', axis=1)
y = df['fraud']

# Train model
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)

# Save model
with open('fraud_model.pkl', 'wb') as f:
    pickle.dump(model, f)

print("Model trained and saved!")

def predict_fraud(repair_cost, claim_age_days, previous_claims,
                  location_match, image_duplicate):

    # Load model
    with open('fraud_model.pkl', 'rb') as f:
        model = pickle.load(f)

    # Input data
    input_data = np.array([[
        repair_cost,
        claim_age_days,
        previous_claims,
        location_match,
        image_duplicate
    ]])

    # Predict
    fraud_probability = model.predict_proba(input_data)[0][1]
    fraud_score = int(fraud_probability * 100)

    # Risk level
    if fraud_score >= 70:
        risk_level = "HIGH"
    elif fraud_score >= 40:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    # Reasons
    reasons = []
    if repair_cost > 50000:
        reasons.append("Suspicious repair cost")
    if image_duplicate == 1:
        reasons.append("Duplicate image detected")
    if previous_claims > 2:
        reasons.append("Multiple previous claims")
    if location_match == 0:
        reasons.append("Location mismatch")
    if claim_age_days > 30:
        reasons.append("Late claim submission")

    return {
        "fraud_score": fraud_score,
        "risk_level": risk_level,
        "reasons": reasons
    }

# Test it
result = predict_fraud(
    repair_cost=85000,
    claim_age_days=45,
    previous_claims=3,
    location_match=0,
    image_duplicate=1
)

print(result)

# Fix the warning - use proper input
import pandas as pd

def predict_fraud(repair_cost, claim_age_days, previous_claims,
                  location_match, image_duplicate):

    with open('fraud_model.pkl', 'rb') as f:
        model = pickle.load(f)

    # Use DataFrame to avoid warning
    input_data = pd.DataFrame([[
        repair_cost,
        claim_age_days,
        previous_claims,
        location_match,
        image_duplicate
    ]], columns=['repair_cost', 'claim_age_days', 'previous_claims',
                 'location_match', 'image_duplicate'])

    fraud_probability = model.predict_proba(input_data)[0][1]
    fraud_score = int(fraud_probability * 100)

    if fraud_score >= 70:
        risk_level = "HIGH"
    elif fraud_score >= 40:
        risk_level = "MEDIUM"
    else:
        risk_level = "LOW"

    reasons = []
    if repair_cost > 50000:
        reasons.append("Suspicious repair cost")
    if image_duplicate == 1:
        reasons.append("Duplicate image detected")
    if previous_claims > 2:
        reasons.append("Multiple previous claims")
    if location_match == 0:
        reasons.append("Location mismatch")
    if claim_age_days > 30:
        reasons.append("Late claim submission")

    return {
        "fraud_score": fraud_score,
        "risk_level": risk_level,
        "reasons": reasons
    }

# Test again
result = predict_fraud(85000, 45, 3, 0, 1)
print(result)

!pip install flask-ngrok pyngrok

from flask import Flask, request, jsonify
from pyngrok import ngrok
import threading

app = Flask(__name__)

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.get_json()

    repair_cost = data.get('repair_cost', 0)
    claim_age_days = data.get('claim_age_days', 0)
    previous_claims = data.get('previous_claims', 0)
    location_match = data.get('location_match', 1)
    image_duplicate = data.get('image_duplicate', 0)

    result = predict_fraud(
        repair_cost,
        claim_age_days,
        previous_claims,
        location_match,
        image_duplicate
    )

    return jsonify(result)

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "running", "service": "fraud-ai-service"})

# Start ngrok tunnel
public_url = ngrok.connect(5000)
print(f"Public URL: {public_url}")

# Run Flask
threading.Thread(target=app.run, kwargs={"port": 5000}).start()

from flask import Flask, request, jsonify
import threading

app = Flask(__name__)

@app.route('/analyze', methods=['POST'])
def analyze():
    data = request.get_json()
    repair_cost = data.get('repair_cost', 0)
    claim_age_days = data.get('claim_age_days', 0)
    previous_claims = data.get('previous_claims', 0)
    location_match = data.get('location_match', 1)
    image_duplicate = data.get('image_duplicate', 0)
    result = predict_fraud(repair_cost, claim_age_days, previous_claims, location_match, image_duplicate)
    return jsonify(result)

@app.route('/health', methods=['GET'])
def health():
    return jsonify({"status": "running"})

# Run in background thread
t = threading.Thread(target=app.run, kwargs={"port": 5000})
t.daemon = True
t.start()
print("Flask running in background!")

import requests

response = requests.post('http://127.0.0.1:5000/analyze',
    json={
        "repair_cost": 85000,
        "claim_age_days": 45,
        "previous_claims": 3,
        "location_match": 0,
        "image_duplicate": 1
    })

print(response.json())